---
application:
  name: "dockertest"
  project: "Programming"
  organization: "QoveryCommunity"
routers:
- name: "main-dockertest"
  routes:
  - application_name: "dockertest"
    paths:
    - "/*"

